pipeline {


  agent{
      docker{
         image 'maven:3.6.1-jdk-8-slim'
         args '-v $HOME/.m2:/root/.m2'
      }
  }

  stages{
      stage(build){
          when {
            changeset "**/worker/**"
          }
          steps{
              echo 'compiling worker app'
              dir('worker'){
                sh 'mvn compile'
              }
          }
      }
      stage(test){
          when {
            changeset "**/worker/**"
          }
          steps{
              echo 'testing worker app'
              dir('worker'){
                sh 'mvn clean test'
              }
          }
      }
      stage(package){
           when {
             branch "master"
             changeset "**/worker/**"
          }

          steps{
              echo 'packaging worker app'
              dir('worker'){
                sh 'mvn package -DskipTests'
              }
          }
      }
  }

  post{
    always{
        echo 'This pipeline is completed..'
    }
  }
}
